services:
  - type: web
    name: finge-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd server && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7 